// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2iRpoJjjRdsgHZxM3lnNOaSGYhnHF7pI',
    appId: '1:991604351159:web:56b6fe1a8bbdaee752ad32',
    messagingSenderId: '991604351159',
    projectId: 'split-spot-4934d',
    authDomain: 'split-spot-4934d.firebaseapp.com',
    storageBucket: 'split-spot-4934d.firebasestorage.app',
    measurementId: 'G-3STPP30RRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCEZWFs2H1_LgCt9Zfn6Tto4334b0eVI',
    appId: '1:991604351159:android:d901443ce975ab6b52ad32',
    messagingSenderId: '991604351159',
    projectId: 'split-spot-4934d',
    storageBucket: 'split-spot-4934d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQr1QudtM-3DEFzcIvSkCEICi4VXIUYY',
    appId: '1:991604351159:ios:5822d4add143b69d52ad32',
    messagingSenderId: '991604351159',
    projectId: 'split-spot-4934d',
    storageBucket: 'split-spot-4934d.firebasestorage.app',
    iosBundleId: 'com.example.splitspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQr1QudtM-3DEFzcIvSkCEICi4VXIUYY',
    appId: '1:991604351159:ios:5822d4add143b69d52ad32',
    messagingSenderId: '991604351159',
    projectId: 'split-spot-4934d',
    storageBucket: 'split-spot-4934d.firebasestorage.app',
    iosBundleId: 'com.example.splitspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2iRpoJjjRdsgHZxM3lnNOaSGYhnHF7pI',
    appId: '1:991604351159:web:28cf3901b8d61c4f52ad32',
    messagingSenderId: '991604351159',
    projectId: 'split-spot-4934d',
    authDomain: 'split-spot-4934d.firebaseapp.com',
    storageBucket: 'split-spot-4934d.firebasestorage.app',
    measurementId: 'G-1DF6G1DVCC',
  );

}